### ISSUE TITLE
Bar not fully filled

### ISSUE THREAD

**Issue by cool-Blue** [maqsoftware/HorizontalFunnel#8]
The first bar is only partially filled.
![image](https://user-images.githubusercontent.com/8417135/92813325-52895580-f404-11ea-8e7b-884f9150dcdf.png)
The grey bar should extend accross to the red X.
If I filter out the first element of the series, the problem moves to the next bar when it becomes the first.
This is depends on the height of the visual.  If the first bar is taller than wider, there is no problem...
![image](https://user-images.githubusercontent.com/8417135/92813970-a9435f00-f405-11ea-9a47-61224921d4be.png)
As the height is reduced such that the height of the first bar is less than it's width, it bar remains square aspect ratio.

**Comment by Xtinction** [comment]
![image](https://user-images.githubusercontent.com/9572901/94249648-79757a80-ff20-11ea-8f0f-ae0cf0ebd2eb.png)
Same Issue here, the first block is just cut off halfway though.

**Comment by NainakshiB** [comment]
Hello @cool-Blue / @Xtinction , 

We have fixed the issue in visual.

However, the publish process will take considerable amount of time for the changes to be published on AppSource.

We will let you know when the build will be published to AppSource.

If you have an urgent requirement, feel free to reach out to us for private build via [Support ](support@maqsoftware.com)

Thanks,
Nainakshi Batra
MAQ Software

**Comment by cool-Blue** [comment]
Hi I can confirm that the issue is fixed.  Closing.
